#include<stdio.h>

/*
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t. 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added

*/
int get_sum_ascii_characters(char* s){
  int sum = s[0];
  for(int i = 1; s[i] != '\0'; i++){
    sum += s[i];
  }
  return sum;
}
char find_difference(char* s, char* t){
  return get_sum_ascii_characters(t)-get_sum_ascii_characters(s);
}




int main(){
  char* s = "abcd";
  char* t = "abecd";
  printf("%c",find_difference(s,t));
}


